apiVersion: apimanagement.azure.com/v1api20220801
kind: ApiManagementService
metadata:
  name: apim-instance
  namespace: flux-system
spec:
  location: westeurope
  sku:
    name: Developer
    capacity: 1
  publisherEmail: github.com@vanhoutensolutions.nl
  publisherName: JP
  identity:
    type: SystemAssigned