apiVersion: apimanagement.azure.com/v1alpha1
kind: Api
metadata:
  name: demo-api
  namespace: flux-system
spec:
  apiManagementService: apim-instance
  displayName: Demo API
  path: demo
  protocols:
  - https
  serviceUrl: https://jsonplaceholder.typicode.com