apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: aso2
  namespace: flux-system
spec:
  interval: 1h
  url: https://raw.githubusercontent.com/Azure/azure-service-operator/main/v2/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: azure-service-operator
  namespace: flux-system
spec:
  releaseName: azure-service-operator
  chart:
    spec:
      chart: azure-service-operator
      sourceRef:
        kind: HelmRepository
        name: aso2
        namespace: flux-system
      version: "2.*.*"
  interval: 5m
  install:
    createNamespace: true  
  values:
    installCRDs: true
    crdPattern: "resources.azure.com/*;containerservice.azure.com/*;keyvault.azure.com/*;managedidentity.azure.com/*;eventhub.azure.com/*;apimanagement.azure.com/*"
  valuesFrom:
    - kind: Secret
      name: azure-credentials
      valuesKey: tenantId
      targetPath: azureTenantId
    - kind: Secret
      name: azure-credentials
      valuesKey: clientId
      targetPath: azureClientId
    - kind: Secret
      name: azure-credentials
      valuesKey: clientSecret
      targetPath: azureClientSecret