apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: aso2
  namespace: flux-system
spec:
  interval: 1h
  url: https://raw.githubusercontent.com/Azure/azure-service-operator/main/v2/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: azure-service-operator
  namespace: flux-system
spec:
  releaseName: azure-service-operator
  chart:
    spec:
      chart: azure-service-operator
      sourceRef:
        kind: HelmRepository
        name: aso2
        namespace: flux-system
      version: "2.*.*"
  interval: 5m
  install:
    createNamespace: true  
  values:
    installCRDs: true
    crdPattern: "resources.azure.com/*;containerservice.azure.com/*;keyvault.azure.com/*;managedidentity.azure.com/*;eventhub.azure.com/*;apimanagement.azure.com/*"
    webhook:
      tls:
        enabled: true
        certManager:
          enabled: true
  valuesFrom:
    - kind: Secret
      name: azure-credentials
      valuesKey: tenantId
      targetPath: azureTenantId
    - kind: Secret
      name: azure-credentials
      valuesKey: clientId
      targetPath: azureClientId
    - kind: Secret
      name: azure-credentials
      valuesKey: clientSecret
      targetPath: azureClientSecret
---
# Create a patch for the ASO webhook configuration
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: azureserviceoperator-validating-webhook-configuration
webhooks:
- name: validate.v1api20220801.services.apimanagement.azure.com
  clientConfig:
    service:
      name: azureserviceoperator-webhook-service
      namespace: flux-system
      path: /validate-apimanagement-azure-com-v1api20220801-service
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUROVENDQWgyZ0F3SUJBZ0lRYkJMN2Z0TW04QXN0SldRRWdHVk8vakFOQmdrcWhraUc5dzBCQVFzRkFEQUEKTUI0WERUSTFNRFV3TVRFME1ESXhNbG9YRFRJMU1EY3pNREUwTURJeE1sb3dBRENDQVNJd0RRWUpLb1pJaHZjTgpBUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS2g2WUMwNWt2enZETUpseGk2NjFOYXlCc0hhMUYwOTdQL2dUZmJjClNVQkdWZEVKbjVtTW9DZmxTWU5yNDVRUjl6TTFzR3cwV0oxQWR4TFgrTGU0bTV1dFdXZGZEb3lNRDVaZDNoaloKTlVjdUcyS0hoRVFHTzdOblRxV2UyTGJFYU5qTDBoYmEwR3VYRDEvbWdsVjN0MWRiVEFCcjRYdWM4elRsSUEvMApkdmRrT2lKZWFQZWtnMUp0QWlJS1dFYzhrTDN5cFFlekRzTTZlSDJMcDF1c0phQXJHTENPTU4yNUU4YWczZ3B0Ck8yWWRCWUxtai84bURRNXpqV1ZlZi91YUJsRW5MVHVjWFR0T3ZiOWF1NWt0djhhZXJXZGNqY0luWGdsc3N6MXoKa285Tk1ESlV3OXY5a0ovNTBRZ0lwNk5qMWl0V2JoR0YrT3c5U21nTGxPemUyVUVDQXdFQUFhT0JxakNCcHpBTwpCZ05WSFE4QkFmOEVCQU1DQmFBd0RBWURWUjBUQVFIL0JBSXdBRENCaGdZRFZSMFJBUUgvQkh3d2VvSTBZWHAxCmNtVnpaWEoyYVdObGIzQmxjbUYwYjNJdGQyVmlhRzl2YXkxelpYSjJhV05sTG1ac2RYZ3RjM2x6ZEdWdExuTjIKWTRKQ1lYcDFjbVZ6WlhKMmFXTmxiM0JsY21GMGIzSXRkMlZpYUc5dmF5MXpaWEoyYVdObExtWnNkWGd0YzNsegpkR1Z0TG5OMll5NWpiSFZ6ZEdWeUxteHZZMkZzTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFCWGRsS1FiV0J4ClBPVkZvT1BCR2pmOEM5MlZJcEtxQjJSNFpQYVNBcVYyRGRlSWZaT1c0QnQ2RWJzdDdTSUg3bHpwV01JeEtHNUsKYnk4SEthNldJczF6ZytjOXc2cEpaSmJGZ2JBV3cydE1tSmkvSXI5ZzBjbFNOZkJJQnRTTmU5dngwTnNuWkJHMQpkTUF2eTdQOVByUUwwN2xvM2l0dzlZRWkzdUJRd291dFk2UlBOTnZ6Q0VGT2ZQVVN1ZmRHelF4NjdabmR5TGlKCm5aaGlQSHFRK2xWd0tjWFlWTEY3ZFZvRGcyVmZxcU5qdHJSV0VkYkFsWjJzc0hEaDVzZ01pOGdHbHRjQWxDMUYKNDEvQ1k1ZEU5V0VQMDgweWR4a09UbEY2VnI0UVVRa3VDWHIwNWJCbU9DRkF0TkQzN0I3dU4zL1V6eSt1MENEcQo5RTlGNWYxN0ordHYKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  sideEffects: None
  admissionReviewVersions: ["v1"]
  failurePolicy: Fail
  timeoutSeconds: 30  # Increase timeout for better reliability