apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-service-operator
  namespace: flux-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-service-operator
  template:
    metadata:
      labels:
        app: azure-service-operator
    spec:
      containers:
      - name: operator
        image: mcr.microsoft.com/oss/azure/azure-service-operator:v2.0.0
        args:
        - --settings=configmap
        env:
        - name: AZURE_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: azure-credentials
              key: tenantId
        - name: AZURE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: azure-credentials
              key: clientId
        - name: AZURE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: azure-credentials
              key: clientSecret
      restartPolicy: Always