apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flux-applier-role
  namespace: cert-manager
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flux-applier-rolebinding
  namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flux-applier-role
subjects:
  - kind: ServiceAccount
    name: flux-applier
    namespace: cert-manager